# Generated by Django 5.1.2 on 2024-10-31 13:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trailer',
            field=models.FileField(blank=True, help_text='Upload a trailer video (up to 100MB)', null=True, upload_to='course_trailers/', validators=[app.models.validate_video_file_size]),
        ),
    ]
