# Generated by Django 5.1.2 on 2024-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('chat_id', models.CharField(help_text='Telegram group chat ID', max_length=50)),
            ],
        ),
    ]
