# Generated by Django 5.1.2 on 2024-10-31 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_helpgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='help_group',
            field=models.ForeignKey(blank=True, help_text='Select the Telegram group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.helpgroup'),
        ),
    ]
